name: cached_video_player
description: A new flutter plugin that is virtually a clone of official video_player plugin except that it supports caching( Android and iOS)
version: 2.0.0
#homepage: https://github.com/vikram25897/flutter_cached_video_player
homepage: https://github.com/Yongle-Fu/flutter_cached_video_player
publish_to: http://dart-pub.brainco.cn:8081

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.cached_video_player
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: CachedVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.3.0
#  video_player_platform_interface: ^4.1.0
#  video_player_web: ^2.0.3

  video_player_web:
    version: "^2.0.0+1"
    hosted:
      name: video_player_web
      url: http://dart-pub.brainco.cn:8081

  video_player_platform_interface:
    version: "^4.1.0+1"
    hosted:
      name: video_player_platform_interface
      url: http://dart-pub.brainco.cn:8081

  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
  pigeon: ^0.1.21

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.0
